"""adds sender and receiver column to message

Revision ID: 2c8342b868c4
Revises: 8770c8d57bac
Create Date: 2023-08-16 16:11:19.564609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8342b868c4'
down_revision = '8770c8d57bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
